# Generated by Django 2.0.5 on 2020-03-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book01', '0002_pagedemo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=30)),
            ],
        ),
    ]
