# Generated by Django 2.0 on 2020-03-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book01', '0003_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
    ]
